<template>
  <div>
    <div class="page-header"><div><div class="page-title">لیست انتظار اهداکنندگان</div><div class="page-subtitle">مدیریت ورود اهداکنندگان واجد شرایط به استخر Matching</div></div><button class="btn btn-secondary" @click="load"><i class="ri-refresh-line"></i> به‌روزرسانی</button></div>
    <div v-if="error" class="alert alert-danger"><i class="ri-error-warning-line"></i>{{ error }}</div>
    <div class="summary-grid"><div class="summary-card"><span>کل نتایج</span><strong>{{ toFa(pagination.count) }}</strong></div><div class="summary-card active"><span>در دسترس در این صفحه</span><strong>{{ toFa(count('available')) }}</strong></div><div class="summary-card candidate"><span>فرایند تطبیق در صفحه</span><strong>{{ toFa(matchingCount) }}</strong></div><div class="summary-card inactive"><span>معلق/منع دائم در صفحه</span><strong>{{ toFa(inactiveCount) }}</strong></div></div>
    <section class="card filters"><div class="form-group"><label class="form-label">جستجو</label><input v-model="search" class="form-input" placeholder="نام یا کد ملی" @keyup.enter="load(1)"></div><div class="form-group"><label class="form-label">وضعیت</label><select v-model="statusFilter" class="form-input" @change="load(1)"><option value="">همه وضعیت‌ها</option><option v-for="(label,key) in statusLabels" :key="key" :value="key">{{ label }}</option></select></div><button class="btn btn-primary" @click="load(1)">اعمال</button></section>
    <section class="card"><div v-if="loading" class="empty-state"><i class="ri-loader-4-line spin"></i><p>در حال بارگذاری…</p></div><div v-else class="table-wrap"><table><thead><tr><th>اهداکننده</th><th>گروه خونی</th><th>نوع</th><th>وضعیت</th><th>عملیات</th></tr></thead><tbody><tr v-for="item in filtered" :key="item._id"><td><strong>{{ item.fullName }}</strong><small>{{ toFa(item.nationalId) }}</small></td><td dir="ltr">{{ item.bloodType }}{{ item.rhFactor==='positive'?'+':'-' }}</td><td>{{ item.donorType==='living_related'?'زنده خویشاوند':'زنده غیرخویشاوند' }}</td><td><span :class="['status',item.status]">{{ item.statusDisplay }}</span></td><td><div class="row-actions"><button v-if="canManage&&item.allowedTransitions.includes('available')" class="btn btn-primary btn-sm" @click="addToWaiting(item)"><i class="ri-user-add-line"></i> افزودن به لیست انتظار</button><button v-if="canManage&&item.allowedTransitions.includes('suspended')" class="btn btn-secondary btn-sm" @click="leaveWaiting(item)"><i class="ri-pause-line"></i> خروج موقت</button><button v-if="canManage&&item.allowedTransitions.length" class="icon-action" title="تغییر وضعیت" @click="openStatus(item)"><i class="ri-arrow-left-right-line"></i></button><button class="icon-action" title="پرونده" @click="$router.push(`/donors/${item._id}`)"><i class="ri-eye-line"></i></button></div></td></tr></tbody></table><div v-if="!filtered.length" class="empty-state"><i class="ri-list-check-2-line"></i><p>موردی یافت نشد.</p></div><pagination-controls :pagination="pagination" @change="load" /></div></section>
    <div v-if="canManage&&statusModal" class="modal-overlay" @click.self="statusModal=false"><div class="modal small-modal"><div class="modal-header"><h3>تغییر وضعیت {{ current.fullName }}</h3><button class="modal-close" @click="statusModal=false"><i class="ri-close-line"></i></button></div><div class="form-group"><label class="form-label">وضعیت بعدی</label><select v-model="nextStatus" class="form-input"><option value="">انتخاب کنید</option><option v-for="key in current.allowedTransitions" :key="key" :value="key">{{ statusLabels[key]||key }}</option></select></div><div class="form-group"><label class="form-label">دلیل تغییر</label><textarea v-model="reason" class="form-input" rows="4"></textarea></div><div class="modal-footer"><button class="btn btn-secondary" @click="statusModal=false">لغو</button><button class="btn btn-primary" :disabled="saving||!nextStatus||!reason.trim()" @click="saveStatus">ثبت</button></div></div></div>
  </div>
</template>
<script setup>
import { computed,onMounted,ref } from 'vue'
import { registryApi } from '../services/api'
import { useAuth } from '../composables/useAuth'
import { toFaDigits } from '../utils/date'
import PaginationControls from '../components/PaginationControls.vue'
const {authState}=useAuth(),toFa=toFaDigits,canManage=computed(()=>authState.user?.can_manage_clinical_workflow===true)
const statusLabels={registered:'ثبت‌نام اولیه',medical_screening:'در غربالگری پزشکی',available:'در دسترس برای Matching',match_candidate:'کاندیدای اهدا',awaiting_crossmatch:'در انتظار Cross-Match',ready:'آماده عمل',donated:'اهدا انجام شد',follow_up:'پیگیری پس از اهدا',reserved:'رزرو شده',suspended:'معلق',permanent_deferral:'منع دائم پزشکی'}
const donors=ref([]),loading=ref(false),saving=ref(false),error=ref(''),search=ref(''),statusFilter=ref(''),statusModal=ref(false),current=ref({}),nextStatus=ref(''),reason=ref(''),pagination=ref({page:1,pages:1,count:0,has_next:false,has_previous:false})
const filtered=computed(()=>donors.value),count=status=>donors.value.filter(item=>item.status===status).length,matchingCount=computed(()=>donors.value.filter(item=>['match_candidate','awaiting_crossmatch','ready','reserved'].includes(item.status)).length),inactiveCount=computed(()=>donors.value.filter(item=>['suspended','permanent_deferral'].includes(item.status)).length)
async function load(page=pagination.value.page||1){loading.value=true;error.value='';try{const response=await registryApi.listDonors({page,page_size:25,search:search.value,status:statusFilter.value});donors.value=response.donors;pagination.value=response.pagination}catch(e){error.value=e.message}finally{loading.value=false}}
function openStatus(item){current.value=item;nextStatus.value='';reason.value='';statusModal.value=true}function replace(item){const index=donors.value.findIndex(row=>row._id===item._id);if(index>=0)donors.value[index]=item}
async function change(item,status,why){saving.value=true;try{const response=await registryApi.updateDonorStatus(item._id,status,why);replace(response.donor);statusModal.value=false;window.toast?.add({severity:'success',summary:'وضعیت',detail:response.message})}catch(e){error.value=e.message}finally{saving.value=false}}
const addToWaiting=item=>change(item,'available','افزودن اهداکننده واجد شرایط به لیست انتظار و استخر Matching')
const leaveWaiting=item=>change(item,'suspended','خروج موقت اهداکننده از لیست انتظار')
const saveStatus=()=>change(current.value,nextStatus.value,reason.value)
onMounted(load)
</script>
<style scoped>
.page-header,.filters,.row-actions{display:flex;align-items:center;justify-content:space-between;gap:14px}.page-header{align-items:flex-start;margin-bottom:20px}.summary-grid{display:grid;grid-template-columns:repeat(4,1fr);gap:12px;margin-bottom:14px}.summary-card,.card{background:var(--surface);border:1px solid var(--border);border-radius:var(--radius-lg);padding:18px;box-shadow:var(--shadow-1)}.summary-card{border-top:3px solid var(--text-3)}.summary-card.active{border-top-color:#22c55e}.summary-card.candidate{border-top-color:var(--color-primary)}.summary-card.inactive{border-top-color:#f59e0b}.summary-card span,.summary-card strong{display:block}.summary-card span{color:var(--text-2)}.summary-card strong{font-size:24px}.filters{justify-content:flex-start;margin-bottom:14px}.filters .form-group{margin:0;min-width:240px}.table-wrap{overflow:auto}table{width:100%;border-collapse:collapse;white-space:nowrap}th,td{padding:11px;border-bottom:1px solid var(--border);text-align:right}th{font-size:12px;color:var(--text-2);background:var(--surface-muted)}td small{display:block;color:var(--text-3)}.status{padding:4px 8px;border-radius:999px;background:var(--surface-muted);font-size:11px}.status.available{background:#dcfce7;color:#166534}.status.suspended,.status.permanent_deferral{background:#fee2e2;color:#991b1b}.row-actions{justify-content:flex-start;gap:5px}.icon-action{width:31px;height:31px;border:1px solid var(--border);border-radius:8px;background:var(--surface);cursor:pointer}.small-modal{max-width:520px}.spin{animation:spin 1s linear infinite}@media(max-width:850px){.summary-grid{grid-template-columns:repeat(2,1fr)}.filters{flex-direction:column;align-items:stretch}.filters .form-group{min-width:0}}
</style>
