<template>
  <section class="temporary-matcher">
    <div class="matcher-heading"><div><h3><i class="ri-flashlight-line"></i> سازگاری‌سنجی موقت HLA</h3><p>داده‌ها فقط در مرورگر پردازش می‌شوند و در پرونده یا سرور ذخیره نخواهند شد.</p></div><button class="btn btn-secondary btn-sm" @click="addCandidate"><i class="ri-add-line"></i> نمونه موقت</button></div>
    <div class="candidate-list"><article v-for="(candidate,index) in candidates" :key="candidate.id" class="candidate-card"><div class="candidate-title"><input v-model="candidate.label" class="form-input" :placeholder="`نمونه ${index+1}`"><button class="icon-btn" :disabled="candidates.length===1" @click="removeCandidate(index)"><i class="ri-delete-bin-line"></i></button></div><div class="hla-input-grid"><div v-for="field in fields" :key="field.key" class="form-group"><label class="form-label">{{ field.label }}</label><checkbox-multi-select v-model="candidate[field.key]" :options="field.options" :max-selected="2" :max-chips="2" :ltr="true" placeholder="حداکثر دو آلل"></checkbox-multi-select></div></div></article></div>
    <div class="result-table-wrap"><table><thead><tr><th>نمونه</th><th>شباهت HLA</th><th>Anti-HLA مستقیم</th><th>هم‌پوشانی خودی</th><th>CREG بالقوه</th><th>جمع‌بندی</th></tr></thead><tbody><tr v-for="result in results" :key="result.id"><td><strong>{{ result.label||'بدون نام' }}</strong></td><td class="tooltip-anchor" :title="buildHlaTooltip({loci:result.loci,total_matches:result.matches,maximum:result.maximum,percent:result.percent})">{{ result.matches }}/{{ result.maximum }} · {{ result.percent }}٪<div v-if="similarityChips(result).length" class="similarity-row"><span v-for="chip in similarityChips(result)" :key="chip.key" class="similarity-chip" :title="chip.title">{{ chip.label }}</span></div></td><td><span v-if="result.exactConflicts.length" class="conflict-list" :title="result.exactConflicts.join('، ')">{{ result.exactConflicts.join('، ') }}</span><span v-else>ندارد</span></td><td><span v-if="result.selfOverlapConflicts.length" class="conditional-list" :title="result.selfOverlapConflicts.join('، ')">{{ result.selfOverlapConflicts.join('، ') }} · نیازمند High-Resolution</span><span v-else>ندارد</span></td><td><span v-if="result.cregPotential.length" class="creg-list" :title="result.cregPotential.map(item=>`${item.antigen} (${item.groups.join('/')})`).join('، ')">{{ result.cregPotential.map(item=>`${item.antigen} (${item.groups.join('/')})`).join('، ') }}</span><span v-else>ندارد</span></td><td><span :class="['badge',tone(result.status)]" :title="label(result.status)">{{ label(result.status) }}</span></td></tr></tbody></table></div>
    <div class="matcher-note"><i class="ri-shield-check-line"></i>این محاسبه سریع و مقدماتی است و جایگزین Matching موتور مرکزی یا Cross-Match آزمایشگاهی نیست.</div>
  </section>
</template>
<script setup>
import { computed, reactive } from 'vue'
import CheckboxMultiSelect from './CheckboxMultiSelect.vue'
import { hlaOptions } from '../data/hlaOptions'
import { evaluateTemporaryCandidates } from '../services/temporaryMatching'
import { buildHlaTooltip, buildSimilarityChips } from '../utils/matching'
const props=defineProps({recipient:{type:Object,required:true}})
let nextId=1
const blank=()=>({id:nextId++,label:'',hla_a:[],hla_b:[],hla_c:[],hla_drb1:[],hla_dqb1:[],hla_drb:[]})
const candidates=reactive([blank()])
const fields=[{key:'hla_a',label:'HLA-A',options:hlaOptions.hlaA},{key:'hla_b',label:'HLA-B',options:hlaOptions.hlaB},{key:'hla_c',label:'HLA-C',options:hlaOptions.hlaC},{key:'hla_drb1',label:'HLA-DRB1',options:hlaOptions.hlaDRB1},{key:'hla_dqb1',label:'HLA-DQB1',options:hlaOptions.hlaDQB1},{key:'hla_drb',label:'HLA-DRB3/4/5',options:hlaOptions.hlaDRB}]
const results=computed(()=>evaluateTemporaryCandidates(props.recipient,candidates))
function addCandidate(){candidates.push(blank())}function removeCandidate(index){if(candidates.length>1)candidates.splice(index,1)}
const similarityChips = summary => buildSimilarityChips(summary)
const tone=status=>status==='compatible'?'badge-success':status==='conditional'?'badge-warning':'badge-danger',label=status=>status==='compatible'?'سازگار مقدماتی':status==='conditional'?'مشروط به بررسی تکمیلی':status==='insufficient-data'?'اطلاعات ناکافی':'ناسازگار Anti-HLA'
</script>
<style scoped>
.temporary-matcher{display:grid;gap:14px;padding:16px;border:1px dashed var(--color-primary);border-radius:var(--radius-lg);background:var(--color-primary-soft)}.matcher-heading,.candidate-title{display:flex;align-items:center;justify-content:space-between;gap:10px}.matcher-heading h3{margin:0}.matcher-heading p{margin:4px 0 0;color:var(--text-2);font-size:12px}.candidate-list{display:grid;gap:10px}.candidate-card{padding:12px;background:var(--surface);border:1px solid var(--border);border-radius:var(--radius-md)}.candidate-title{margin-bottom:10px}.candidate-title .form-input{max-width:260px}.hla-input-grid{display:grid;grid-template-columns:repeat(5,minmax(0,1fr));gap:8px}.result-table-wrap{overflow:auto;background:var(--surface);border-radius:var(--radius-md)}table{width:100%;border-collapse:collapse;white-space:nowrap}th,td{padding:10px;border-bottom:1px solid var(--border);text-align:right}th{background:var(--surface-muted);font-size:12px}.conflict-list{color:#b91c1c;font-weight:700}.conditional-list,.creg-list{color:#c2410c;font-weight:700}.matcher-note{display:flex;gap:6px;color:var(--text-2);font-size:11px}.similarity-row{display:flex;flex-wrap:wrap;gap:6px;margin-top:6px}.similarity-chip{display:inline-flex;align-items:center;padding:3px 10px;border:1px solid #ef4444;border-radius:999px;background:#fff7f7;color:#dc2626;font-size:11px;font-weight:800;cursor:help}@media(max-width:1050px){.hla-input-grid{grid-template-columns:repeat(2,1fr)}}@media(max-width:600px){.hla-input-grid{grid-template-columns:1fr}.matcher-heading{align-items:flex-start;flex-direction:column}}
</style>
