# Generated by Django 5.2.6 on 2026-08-06 06:46

import django.core.validators
import django.db.models.deletion
import registry.validators
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("users", "0002_user_notify_email_approvals_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Person",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "citizenship",
                    models.CharField(
                        choices=[("iranian", "ایرانی"), ("foreign", "غیر ایرانی")],
                        max_length=8,
                    ),
                ),
                (
                    "identifier",
                    models.CharField(
                        max_length=40, verbose_name="کد ملی یا شماره گذرنامه"
                    ),
                ),
                ("first_name", models.CharField(max_length=150, verbose_name="نام")),
                (
                    "last_name",
                    models.CharField(max_length=150, verbose_name="نام خانوادگی"),
                ),
                (
                    "gender",
                    models.CharField(
                        choices=[("male", "مرد"), ("female", "زن")],
                        max_length=6,
                        verbose_name="جنسیت",
                    ),
                ),
                ("birth_date", models.DateField(verbose_name="تاریخ تولد")),
                (
                    "blood_group",
                    models.CharField(
                        choices=[
                            ("A+", "A+"),
                            ("A-", "A-"),
                            ("B+", "B+"),
                            ("B-", "B-"),
                            ("AB+", "AB+"),
                            ("AB-", "AB-"),
                            ("O+", "O+"),
                            ("O-", "O-"),
                        ],
                        max_length=3,
                        verbose_name="گروه خونی و Rh",
                    ),
                ),
                (
                    "phone",
                    models.CharField(
                        max_length=11,
                        validators=[registry.validators.validate_iranian_mobile],
                        verbose_name="شماره موبایل",
                    ),
                ),
                (
                    "emergency_contact_phone",
                    models.CharField(
                        blank=True,
                        max_length=11,
                        validators=[registry.validators.validate_iranian_mobile],
                        verbose_name="شماره موبایل اضطراری",
                    ),
                ),
                (
                    "nationality",
                    models.CharField(blank=True, max_length=100, verbose_name="ملیت"),
                ),
                (
                    "education",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("below_diploma", "زیر دیپلم"),
                            ("diploma", "دیپلم"),
                            ("bachelor", "کاردانی/کارشناسی"),
                            ("postgraduate", "تحصیلات تکمیلی"),
                        ],
                        max_length=20,
                        verbose_name="تحصیلات",
                    ),
                ),
                (
                    "insurance",
                    models.JSONField(
                        blank=True, default=list, verbose_name="بیمه\u200cها"
                    ),
                ),
                (
                    "marital_status",
                    models.CharField(
                        blank=True,
                        choices=[("single", "مجرد"), ("married", "متأهل")],
                        max_length=10,
                        verbose_name="وضعیت تأهل",
                    ),
                ),
                (
                    "weight_kg",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=5,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(500),
                        ],
                        verbose_name="وزن (کیلوگرم)",
                    ),
                ),
                (
                    "height_cm",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=5,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(300),
                        ],
                        verbose_name="قد (سانتی\u200cمتر)",
                    ),
                ),
                (
                    "is_smoker",
                    models.BooleanField(default=False, verbose_name="سیگاری"),
                ),
                (
                    "has_addiction",
                    models.BooleanField(default=False, verbose_name="سابقه اعتیاد"),
                ),
                (
                    "has_alcohol",
                    models.BooleanField(default=False, verbose_name="مصرف الکل"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "center",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="registered_people",
                        to="users.center",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="registered_people",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "فرد",
                "verbose_name_plural": "افراد",
                "ordering": ("-created_at",),
            },
        ),
        migrations.CreateModel(
            name="HLATyping",
            fields=[
                (
                    "person",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="hla_typing",
                        serialize=False,
                        to="registry.person",
                    ),
                ),
                ("hla_a", models.JSONField(blank=True, default=list)),
                ("hla_b", models.JSONField(blank=True, default=list)),
                ("hla_c", models.JSONField(blank=True, default=list)),
                ("hla_drb1", models.JSONField(blank=True, default=list)),
                ("hla_dqb1", models.JSONField(blank=True, default=list)),
                ("hla_drb", models.JSONField(blank=True, default=list)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "تایپ HLA",
                "verbose_name_plural": "تایپ\u200cهای HLA",
            },
        ),
        migrations.CreateModel(
            name="LabTest",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("cdc_pra", "CDC PRA"),
                            ("anti_hla", "Anti-HLA"),
                            ("routine", "آزمایش روتین"),
                            ("viral", "آزمایش ویروسی"),
                        ],
                        max_length=16,
                    ),
                ),
                ("category", models.CharField(blank=True, max_length=120)),
                ("name", models.CharField(max_length=160)),
                ("result", models.JSONField(blank=True, null=True)),
                ("details", models.JSONField(blank=True, default=dict)),
                ("batch_key", models.CharField(blank=True, max_length=160)),
                ("performed_at", models.DateField()),
                ("expires_at", models.DateField(editable=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="registered_lab_tests",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "person",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lab_tests",
                        to="registry.person",
                    ),
                ),
            ],
            options={
                "verbose_name": "نتیجه آزمایش",
                "verbose_name_plural": "نتایج آزمایش\u200cها",
                "ordering": ("-performed_at", "kind", "category", "name"),
            },
        ),
        migrations.CreateModel(
            name="MedicalApproval",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "specialty",
                    models.CharField(
                        choices=[
                            ("nephrologist", "نفرولوژیست"),
                            ("dentist", "دندانپزشک"),
                            ("cardiologist", "متخصص قلب"),
                            ("gastroenterologist", "متخصص گوارش"),
                            ("urologist", "اورولوژیست"),
                        ],
                        max_length=24,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("approved", "تأیید"),
                            ("rejected", "رد"),
                            ("on_hold", "در انتظار"),
                        ],
                        default="on_hold",
                        max_length=10,
                    ),
                ),
                ("approval_date", models.DateField(blank=True, null=True)),
                ("doctor_name", models.CharField(blank=True, max_length=200)),
                ("medical_code", models.CharField(blank=True, max_length=30)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "person",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="medical_approvals",
                        to="registry.person",
                    ),
                ),
            ],
            options={
                "verbose_name": "تأییدیه پزشکی",
                "verbose_name_plural": "تأییدیه\u200cهای پزشکی",
            },
        ),
        migrations.CreateModel(
            name="RecipientProfile",
            fields=[
                (
                    "person",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="recipient_profile",
                        serialize=False,
                        to="registry.person",
                    ),
                ),
                (
                    "transplant_candidate",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("1st", "پیوند اول"),
                            ("2nd", "پیوند دوم"),
                            ("3rd", "پیوند سوم"),
                            ("4th", "پیوند چهارم"),
                        ],
                        max_length=3,
                    ),
                ),
                ("donor_living", models.BooleanField(default=False)),
                ("donor_deceased", models.BooleanField(default=False)),
                ("has_dialysis_history", models.BooleanField(default=False)),
                (
                    "dialysis_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("hemodialysis", "همودیالیز"),
                            ("peritoneal", "دیالیز صفاقی"),
                        ],
                        max_length=20,
                    ),
                ),
                ("dialysis_start_date", models.DateField(blank=True, null=True)),
                ("has_blood_transfusion", models.BooleanField(default=False)),
                (
                    "blood_transfusion_units",
                    models.PositiveSmallIntegerField(blank=True, null=True),
                ),
                ("has_pregnancy_history", models.BooleanField(default=False)),
                (
                    "pregnancy_count",
                    models.PositiveSmallIntegerField(blank=True, null=True),
                ),
                ("has_abortion_history", models.BooleanField(default=False)),
                (
                    "abortion_count",
                    models.PositiveSmallIntegerField(blank=True, null=True),
                ),
                ("previous_transplant", models.BooleanField(default=False)),
                ("previous_transplant_details", models.TextField(blank=True)),
                ("drug_history", models.TextField(blank=True)),
                ("has_drug_allergy", models.BooleanField(default=False)),
                ("drug_allergy_details", models.TextField(blank=True)),
                ("underlying_diseases", models.TextField(blank=True)),
                ("family_kidney_disease", models.BooleanField(default=False)),
                ("family_kidney_disease_details", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "پرونده گیرنده",
                "verbose_name_plural": "پرونده\u200cهای گیرندگان",
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            ("donor_living", True),
                            ("donor_deceased", True),
                            _connector="OR",
                        ),
                        name="registry_recipient_has_donor_source",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="DonorProfile",
            fields=[
                (
                    "person",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="donor_profile",
                        serialize=False,
                        to="registry.person",
                    ),
                ),
                ("self_diabetes_history", models.BooleanField(default=False)),
                ("self_hypertension_history", models.BooleanField(default=False)),
                ("parent_diabetes_history", models.BooleanField(default=False)),
                ("parent_hypertension_history", models.BooleanField(default=False)),
                ("has_drug_allergy", models.BooleanField(default=False)),
                ("drug_allergy_details", models.TextField(blank=True)),
                ("is_related_recipient_candidate", models.BooleanField(default=False)),
                (
                    "recipient_relationship_group",
                    models.CharField(blank=True, max_length=80),
                ),
                (
                    "recipient_relationship_kind",
                    models.CharField(blank=True, max_length=80),
                ),
                ("recipient_relationship_details", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "preferred_recipient",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="preferred_donors",
                        to="registry.recipientprofile",
                    ),
                ),
            ],
            options={
                "verbose_name": "پرونده اهداکننده",
                "verbose_name_plural": "پرونده\u200cهای اهداکنندگان",
            },
        ),
        migrations.AddIndex(
            model_name="person",
            index=models.Index(
                fields=["last_name", "first_name"], name="registry_person_name_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="person",
            index=models.Index(
                fields=["center", "created_at"], name="registry_person_center_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="person",
            constraint=models.UniqueConstraint(
                fields=("citizenship", "identifier"),
                name="registry_person_citizenship_identifier_unique",
            ),
        ),
        migrations.AddIndex(
            model_name="labtest",
            index=models.Index(
                fields=["person", "kind", "expires_at"],
                name="registry_lab_validity_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="labtest",
            constraint=models.CheckConstraint(
                condition=models.Q(("expires_at__gte", models.F("performed_at"))),
                name="registry_lab_expiry_after_performed",
            ),
        ),
        migrations.AddConstraint(
            model_name="labtest",
            constraint=models.UniqueConstraint(
                fields=("person", "kind", "performed_at", "category", "name"),
                name="registry_lab_result_unique",
            ),
        ),
        migrations.AddConstraint(
            model_name="medicalapproval",
            constraint=models.UniqueConstraint(
                fields=("person", "specialty"),
                name="registry_person_specialty_approval_unique",
            ),
        ),
    ]
