# Generated by Django 5.2.6 on 2026-08-06 07:21

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


def migrate_existing_immunology_data(apps, schema_editor):
    HLATyping = apps.get_model("registry", "HLATyping")
    HLASelection = apps.get_model("registry", "HLASelection")
    LabTest = apps.get_model("registry", "LabTest")
    CdcPraTest = apps.get_model("registry", "CdcPraTest")
    AntiHlaTest = apps.get_model("registry", "AntiHlaTest")
    AntiHlaSelection = apps.get_model("registry", "AntiHlaSelection")

    hla_fields = {
        "hla_a": "A",
        "hla_b": "B",
        "hla_c": "C",
        "hla_drb1": "DRB1",
        "hla_dqb1": "DQB1",
        "hla_drb": "DRB",
    }
    for typing in HLATyping.objects.all():
        for field_name, locus in hla_fields.items():
            for allele in getattr(typing, field_name) or []:
                HLASelection.objects.get_or_create(
                    typing_id=typing.pk, locus=locus, allele=allele
                )

    cdc_rows = LabTest.objects.filter(kind="cdc_pra").order_by(
        "person_id", "performed_at", "created_at"
    )
    cdc_groups = {}
    for row in cdc_rows:
        cdc_groups.setdefault((row.person_id, row.performed_at), []).append(row)
    for (person_id, performed_at), rows in cdc_groups.items():
        by_name = {row.name: row for row in rows}
        class_i = by_name.get("class_i")
        class_ii = by_name.get("class_ii")
        if not class_i or not class_ii:
            continue
        i_result = class_i.result or {}
        ii_result = class_ii.result or {}
        details = class_i.details or {}
        CdcPraTest.objects.create(
            person_id=person_id,
            created_by_id=class_i.created_by_id,
            performed_at=performed_at,
            expires_at=class_i.expires_at,
            class_i_status=i_result.get("status") or "negative",
            class_i_value=i_result.get("value"),
            class_i_effective_status=i_result.get("effective_status")
            or i_result.get("status")
            or "negative",
            class_i_implicitly_negative=bool(
                i_result.get("is_implicitly_negative", False)
            ),
            class_ii_status=ii_result.get("status") or "negative",
            class_ii_value=ii_result.get("value"),
            class_ii_effective_status=ii_result.get("effective_status")
            or ii_result.get("status")
            or "negative",
            class_ii_implicitly_negative=bool(
                ii_result.get("is_implicitly_negative", False)
            ),
            implicitly_negative=bool(details.get("implicitly_negative", False)),
            antibody_count=details.get("antibody_count"),
        )

    anti_rows = LabTest.objects.filter(kind="anti_hla").order_by(
        "person_id", "performed_at", "created_at"
    )
    anti_groups = {}
    for row in anti_rows:
        anti_groups.setdefault((row.person_id, row.performed_at), []).append(row)
    for (person_id, performed_at), rows in anti_groups.items():
        test = AntiHlaTest.objects.create(
            person_id=person_id,
            created_by_id=rows[0].created_by_id,
            performed_at=performed_at,
            expires_at=rows[0].expires_at,
            class_i_negative=any(
                (row.details or {}).get("isNone")
                and (row.details or {}).get("class") == "I"
                for row in rows
            ),
            class_ii_negative=any(
                (row.details or {}).get("isNone")
                and (row.details or {}).get("class") == "II"
                for row in rows
            ),
        )
        for row in rows:
            details = row.details or {}
            if details.get("isNone") or details.get("antigen") == "None":
                continue
            locus = details.get("locus")
            antigen = details.get("antigen")
            if locus and antigen:
                AntiHlaSelection.objects.get_or_create(
                    test_id=test.pk,
                    locus=locus,
                    antigen=antigen,
                    defaults={
                        "hla_class": details.get("class") or "I",
                        "mfi": details.get("mfi"),
                    },
                )

    LabTest.objects.filter(kind__in=("cdc_pra", "anti_hla")).delete()


class Migration(migrations.Migration):

    dependencies = [
        ("registry", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AntiHlaSelection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "hla_class",
                    models.CharField(
                        choices=[("I", "Class I"), ("II", "Class II")], max_length=2
                    ),
                ),
                (
                    "locus",
                    models.CharField(
                        choices=[
                            ("A", "HLA-A"),
                            ("B", "HLA-B"),
                            ("C", "HLA-C"),
                            ("DRB1", "HLA-DRB1"),
                            ("DQB1", "HLA-DQB1"),
                            ("DRB", "HLA-DRB3/4/5"),
                            ("DQA1", "HLA-DQA1"),
                            ("DPB1", "HLA-DPB1"),
                            ("DPA1", "HLA-DPA1"),
                        ],
                        max_length=4,
                    ),
                ),
                (
                    "antigen",
                    models.CharField(
                        choices=[
                            ("A*01:01", "A*01:01"),
                            ("A*02:01", "A*02:01"),
                            ("A*02:02", "A*02:02"),
                            ("A*02:03", "A*02:03"),
                            ("A*02:05", "A*02:05"),
                            ("A*03:01", "A*03:01"),
                            ("A*11:01", "A*11:01"),
                            ("A*11:02", "A*11:02"),
                            ("A*23:01", "A*23:01"),
                            ("A*24:02", "A*24:02"),
                            ("A*24:03", "A*24:03"),
                            ("A*25:01", "A*25:01"),
                            ("A*26:01", "A*26:01"),
                            ("A*29:01", "A*29:01"),
                            ("A*29:02", "A*29:02"),
                            ("A*30:01", "A*30:01"),
                            ("A*31:01", "A*31:01"),
                            ("A*32:01", "A*32:01"),
                            ("A*33:01", "A*33:01"),
                            ("A*33:03", "A*33:03"),
                            ("A*34:02", "A*34:02"),
                            ("A*36:01", "A*36:01"),
                            ("A*43:01", "A*43:01"),
                            ("A*66:01", "A*66:01"),
                            ("A*66:02", "A*66:02"),
                            ("A*68:01", "A*68:01"),
                            ("A*68:02", "A*68:02"),
                            ("A*69:01", "A*69:01"),
                            ("A*74:01", "A*74:01"),
                            ("A*80:01", "A*80:01"),
                            ("B*07:02", "B*07:02"),
                            ("B*07:03", "B*07:03"),
                            ("B*08:01", "B*08:01"),
                            ("B*13:02", "B*13:02"),
                            ("B*14:01", "B*14:01"),
                            ("B*14:02", "B*14:02"),
                            ("B*15:01", "B*15:01"),
                            ("B*15:02", "B*15:02"),
                            ("B*15:03", "B*15:03"),
                            ("B*15:12", "B*15:12"),
                            ("B*15:13", "B*15:13"),
                            ("B*15:16", "B*15:16"),
                            ("B*15:18", "B*15:18"),
                            ("B*18:01", "B*18:01"),
                            ("B*27:03", "B*27:03"),
                            ("B*27:05", "B*27:05"),
                            ("B*27:08", "B*27:08"),
                            ("B*35:01", "B*35:01"),
                            ("B*35:08", "B*35:08"),
                            ("B*37:01", "B*37:01"),
                            ("B*38:01", "B*38:01"),
                            ("B*39:01", "B*39:01"),
                            ("B*40:01", "B*40:01"),
                            ("B*40:02", "B*40:02"),
                            ("B*41:01", "B*41:01"),
                            ("B*42:01", "B*42:01"),
                            ("B*44:02", "B*44:02"),
                            ("B*44:03", "B*44:03"),
                            ("B*45:01", "B*45:01"),
                            ("B*46:01", "B*46:01"),
                            ("B*47:01", "B*47:01"),
                            ("B*48:01", "B*48:01"),
                            ("B*49:01", "B*49:01"),
                            ("B*50:01", "B*50:01"),
                            ("B*51:01", "B*51:01"),
                            ("B*52:01", "B*52:01"),
                            ("B*53:01", "B*53:01"),
                            ("B*54:01", "B*54:01"),
                            ("B*55:01", "B*55:01"),
                            ("B*55:04", "B*55:04"),
                            ("B*56:01", "B*56:01"),
                            ("B*57:01", "B*57:01"),
                            ("B*58:01", "B*58:01"),
                            ("B*59:01", "B*59:01"),
                            ("B*67:01", "B*67:01"),
                            ("B*73:01", "B*73:01"),
                            ("B*78:01", "B*78:01"),
                            ("B*81:01", "B*81:01"),
                            ("B*82:02", "B*82:02"),
                            ("B*83:01", "B*83:01"),
                            ("C*01:02", "C*01:02"),
                            ("C*02:02", "C*02:02"),
                            ("C*03:02", "C*03:02"),
                            ("C*03:03", "C*03:03"),
                            ("C*03:04", "C*03:04"),
                            ("C*04:01", "C*04:01"),
                            ("C*04:03", "C*04:03"),
                            ("C*05:01", "C*05:01"),
                            ("C*06:02", "C*06:02"),
                            ("C*07:01", "C*07:01"),
                            ("C*07:02", "C*07:02"),
                            ("C*08:01", "C*08:01"),
                            ("C*08:02", "C*08:02"),
                            ("C*12:02", "C*12:02"),
                            ("C*14:02", "C*14:02"),
                            ("C*15:02", "C*15:02"),
                            ("C*16:01", "C*16:01"),
                            ("C*17:01", "C*17:01"),
                            ("C*18:01", "C*18:01"),
                            ("DRB1*01:01", "DRB1*01:01"),
                            ("DRB1*01:02", "DRB1*01:02"),
                            ("DRB1*01:03", "DRB1*01:03"),
                            ("DRB1*03:01", "DRB1*03:01"),
                            ("DRB1*03:02", "DRB1*03:02"),
                            ("DRB1*03:03", "DRB1*03:03"),
                            ("DRB1*04:01", "DRB1*04:01"),
                            ("DRB1*04:02", "DRB1*04:02"),
                            ("DRB1*04:03", "DRB1*04:03"),
                            ("DRB1*04:04", "DRB1*04:04"),
                            ("DRB1*04:05", "DRB1*04:05"),
                            ("DRB1*07:01", "DRB1*07:01"),
                            ("DRB1*08:01", "DRB1*08:01"),
                            ("DRB1*08:02", "DRB1*08:02"),
                            ("DRB1*09:01", "DRB1*09:01"),
                            ("DRB1*10:01", "DRB1*10:01"),
                            ("DRB1*11:01", "DRB1*11:01"),
                            ("DRB1*11:03", "DRB1*11:03"),
                            ("DRB1*11:04", "DRB1*11:04"),
                            ("DRB1*12:01", "DRB1*12:01"),
                            ("DRB1*12:02", "DRB1*12:02"),
                            ("DRB1*13:01", "DRB1*13:01"),
                            ("DRB1*13:03", "DRB1*13:03"),
                            ("DRB1*13:05", "DRB1*13:05"),
                            ("DRB1*14:01", "DRB1*14:01"),
                            ("DRB1*14:03", "DRB1*14:03"),
                            ("DRB1*14:04", "DRB1*14:04"),
                            ("DRB1*15:01", "DRB1*15:01"),
                            ("DRB1*15:02", "DRB1*15:02"),
                            ("DRB1*15:03", "DRB1*15:03"),
                            ("DRB1*16:01", "DRB1*16:01"),
                            ("DRB1*16:02", "DRB1*16:02"),
                            ("DQB1*02:01", "DQB1*02:01"),
                            ("DQB1*02:02", "DQB1*02:02"),
                            ("DQB1*03:01", "DQB1*03:01"),
                            ("DQB1*03:02", "DQB1*03:02"),
                            ("DQB1*03:03", "DQB1*03:03"),
                            ("DQB1*04:01", "DQB1*04:01"),
                            ("DQB1*04:02", "DQB1*04:02"),
                            ("DQB1*05:01", "DQB1*05:01"),
                            ("DQB1*05:02", "DQB1*05:02"),
                            ("DQB1*05:03", "DQB1*05:03"),
                            ("DQB1*06:01", "DQB1*06:01"),
                            ("DQB1*06:02", "DQB1*06:02"),
                            ("DQB1*06:03", "DQB1*06:03"),
                            ("DQB1*06:04", "DQB1*06:04"),
                            ("DRB3*01:01", "DRB3*01:01"),
                            ("DRB3*02:02", "DRB3*02:02"),
                            ("DRB3*03:01", "DRB3*03:01"),
                            ("DRB4*01:01", "DRB4*01:01"),
                            ("DRB5*01:01", "DRB5*01:01"),
                            ("DRB5*02:02", "DRB5*02:02"),
                            ("DQA1*01:01", "DQA1*01:01"),
                            ("DQA1*01:02", "DQA1*01:02"),
                            ("DQA1*01:03", "DQA1*01:03"),
                            ("DQA1*01:04", "DQA1*01:04"),
                            ("DQA1*02:01", "DQA1*02:01"),
                            ("DQA1*03:01", "DQA1*03:01"),
                            ("DQA1*03:02", "DQA1*03:02"),
                            ("DQA1*04:01", "DQA1*04:01"),
                            ("DQA1*05:01", "DQA1*05:01"),
                            ("DQA1*06:01", "DQA1*06:01"),
                            ("DPB1*01:01", "DPB1*01:01"),
                            ("DPB1*02:01", "DPB1*02:01"),
                            ("DPB1*03:01", "DPB1*03:01"),
                            ("DPB1*04:01", "DPB1*04:01"),
                            ("DPB1*04:02", "DPB1*04:02"),
                            ("DPB1*05:01", "DPB1*05:01"),
                            ("DPB1*06:01", "DPB1*06:01"),
                            ("DPB1*09:01", "DPB1*09:01"),
                            ("DPB1*11:01", "DPB1*11:01"),
                            ("DPB1*13:01", "DPB1*13:01"),
                            ("DPB1*14:01", "DPB1*14:01"),
                            ("DPB1*15:01", "DPB1*15:01"),
                            ("DPB1*17:01", "DPB1*17:01"),
                            ("DPB1*18:01", "DPB1*18:01"),
                            ("DPB1*19:01", "DPB1*19:01"),
                            ("DPB1*28:01", "DPB1*28:01"),
                            ("DPA1*01:03", "DPA1*01:03"),
                            ("DPA1*02:01", "DPA1*02:01"),
                            ("DPA1*02:02", "DPA1*02:02"),
                            ("DPA1*03:01", "DPA1*03:01"),
                            ("DPA1*04:01", "DPA1*04:01"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "mfi",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "آنتی\u200cژن انتخاب\u200cشده Anti-HLA",
                "verbose_name_plural": "آنتی\u200cژن\u200cهای انتخاب\u200cشده Anti-HLA",
                "ordering": ("hla_class", "locus", "antigen"),
            },
        ),
        migrations.CreateModel(
            name="AntiHlaTest",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("performed_at", models.DateField()),
                ("expires_at", models.DateField(editable=False)),
                ("class_i_negative", models.BooleanField(default=False)),
                ("class_ii_negative", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "آزمایش Anti-HLA",
                "verbose_name_plural": "آزمایش\u200cهای Anti-HLA",
                "ordering": ("-performed_at", "-created_at"),
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name="CdcPraTest",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("performed_at", models.DateField()),
                ("expires_at", models.DateField(editable=False)),
                (
                    "class_i_status",
                    models.CharField(
                        choices=[("positive", "مثبت"), ("negative", "منفی")],
                        max_length=8,
                    ),
                ),
                (
                    "class_i_value",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=5,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                    ),
                ),
                (
                    "class_i_effective_status",
                    models.CharField(
                        choices=[("positive", "مثبت"), ("negative", "منفی")],
                        max_length=8,
                    ),
                ),
                ("class_i_implicitly_negative", models.BooleanField(default=False)),
                (
                    "class_ii_status",
                    models.CharField(
                        choices=[("positive", "مثبت"), ("negative", "منفی")],
                        max_length=8,
                    ),
                ),
                (
                    "class_ii_value",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=5,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                    ),
                ),
                (
                    "class_ii_effective_status",
                    models.CharField(
                        choices=[("positive", "مثبت"), ("negative", "منفی")],
                        max_length=8,
                    ),
                ),
                ("class_ii_implicitly_negative", models.BooleanField(default=False)),
                ("implicitly_negative", models.BooleanField(default=False)),
                (
                    "antibody_count",
                    models.PositiveSmallIntegerField(blank=True, null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "آزمایش CDC PRA",
                "verbose_name_plural": "آزمایش\u200cهای CDC PRA",
                "ordering": ("-performed_at", "-created_at"),
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name="HLASelection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "locus",
                    models.CharField(
                        choices=[
                            ("A", "HLA-A"),
                            ("B", "HLA-B"),
                            ("C", "HLA-C"),
                            ("DRB1", "HLA-DRB1"),
                            ("DQB1", "HLA-DQB1"),
                            ("DRB", "HLA-DRB"),
                        ],
                        max_length=4,
                    ),
                ),
                (
                    "allele",
                    models.CharField(
                        choices=[
                            ("A*01", "A*01"),
                            ("A*02", "A*02"),
                            ("A*03", "A*03"),
                            ("A*11", "A*11"),
                            ("A*23", "A*23"),
                            ("A*24", "A*24"),
                            ("A*25", "A*25"),
                            ("A*26", "A*26"),
                            ("A*29", "A*29"),
                            ("A*30", "A*30"),
                            ("A*31", "A*31"),
                            ("A*32", "A*32"),
                            ("A*33", "A*33"),
                            ("A*34", "A*34"),
                            ("A*36", "A*36"),
                            ("A*43", "A*43"),
                            ("A*66", "A*66"),
                            ("A*68", "A*68"),
                            ("A*69", "A*69"),
                            ("A*74", "A*74"),
                            ("A*80", "A*80"),
                            ("B*07", "B*07"),
                            ("B*08", "B*08"),
                            ("B*13", "B*13"),
                            ("B*14", "B*14"),
                            ("B*15", "B*15"),
                            ("B*18", "B*18"),
                            ("B*27", "B*27"),
                            ("B*35", "B*35"),
                            ("B*37", "B*37"),
                            ("B*38", "B*38"),
                            ("B*39", "B*39"),
                            ("B*40", "B*40"),
                            ("B*41", "B*41"),
                            ("B*42", "B*42"),
                            ("B*44", "B*44"),
                            ("B*45", "B*45"),
                            ("B*46", "B*46"),
                            ("B*47", "B*47"),
                            ("B*48", "B*48"),
                            ("B*49", "B*49"),
                            ("B*50", "B*50"),
                            ("B*51", "B*51"),
                            ("B*52", "B*52"),
                            ("B*53", "B*53"),
                            ("B*54", "B*54"),
                            ("B*55", "B*55"),
                            ("B*56", "B*56"),
                            ("B*57", "B*57"),
                            ("B*58", "B*58"),
                            ("B*59", "B*59"),
                            ("B*67", "B*67"),
                            ("B*73", "B*73"),
                            ("B*78", "B*78"),
                            ("B*81", "B*81"),
                            ("B*82", "B*82"),
                            ("B*83", "B*83"),
                            ("C*01", "C*01"),
                            ("C*02", "C*02"),
                            ("C*03", "C*03"),
                            ("C*04", "C*04"),
                            ("C*05", "C*05"),
                            ("C*06", "C*06"),
                            ("C*07", "C*07"),
                            ("C*08", "C*08"),
                            ("C*12", "C*12"),
                            ("C*14", "C*14"),
                            ("C*15", "C*15"),
                            ("C*16", "C*16"),
                            ("C*17", "C*17"),
                            ("C*18", "C*18"),
                            ("DRB1*01", "DRB1*01"),
                            ("DRB1*03", "DRB1*03"),
                            ("DRB1*04", "DRB1*04"),
                            ("DRB1*07", "DRB1*07"),
                            ("DRB1*08", "DRB1*08"),
                            ("DRB1*09", "DRB1*09"),
                            ("DRB1*10", "DRB1*10"),
                            ("DRB1*11", "DRB1*11"),
                            ("DRB1*12", "DRB1*12"),
                            ("DRB1*13", "DRB1*13"),
                            ("DRB1*14", "DRB1*14"),
                            ("DRB1*15", "DRB1*15"),
                            ("DRB1*16", "DRB1*16"),
                            ("DQB1*02", "DQB1*02"),
                            ("DQB1*03", "DQB1*03"),
                            ("DQB1*04", "DQB1*04"),
                            ("DQB1*05", "DQB1*05"),
                            ("DQB1*06", "DQB1*06"),
                            ("DRB3", "DRB3"),
                            ("DRB4", "DRB4"),
                            ("DRB5", "DRB5"),
                            ("سایر", "سایر"),
                        ],
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "آلل انتخاب\u200cشده HLA",
                "verbose_name_plural": "آلل\u200cهای انتخاب\u200cشده HLA",
                "ordering": ("locus", "allele"),
            },
        ),
        migrations.RemoveConstraint(
            model_name="person",
            name="registry_person_citizenship_identifier_unique",
        ),
        migrations.AddField(
            model_name="person",
            name="is_active",
            field=models.BooleanField(default=True, verbose_name="فعال"),
        ),
        migrations.AlterField(
            model_name="donorprofile",
            name="recipient_relationship_group",
            field=models.CharField(
                blank=True,
                choices=[
                    ("first_degree", "درجه اول"),
                    ("second_degree", "درجه دوم"),
                    ("stranger", "غریبه"),
                ],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="donorprofile",
            name="recipient_relationship_kind",
            field=models.CharField(
                blank=True,
                choices=[
                    ("father", "پدر"),
                    ("mother", "مادر"),
                    ("brother", "برادر"),
                    ("sister", "خواهر"),
                    ("child", "فرزند"),
                    ("spouse", "همسر"),
                ],
                max_length=12,
            ),
        ),
        migrations.AlterField(
            model_name="labtest",
            name="category",
            field=models.CharField(
                choices=[
                    ("CBC", "CBC"),
                    ("Blood Biochemistry", "Blood Biochemistry"),
                    ("Other Biochemistry", "Other Biochemistry"),
                    ("Thyroid", "Thyroid"),
                    ("Urine 24H", "Urine 24H"),
                    ("آزمایش ادرار", "آزمایش ادرار"),
                    ("بانوان", "بانوان"),
                    ("آزمایش ویروسی", "آزمایش ویروسی"),
                ],
                max_length=120,
            ),
        ),
        migrations.AlterField(
            model_name="labtest",
            name="kind",
            field=models.CharField(
                choices=[("routine", "آزمایش روتین"), ("viral", "آزمایش ویروسی")],
                max_length=16,
            ),
        ),
        migrations.AlterField(
            model_name="labtest",
            name="name",
            field=models.CharField(
                choices=[
                    ("WBC", "WBC"),
                    ("HB", "HB"),
                    ("Hct", "Hct"),
                    ("platelets", "platelets"),
                    ("Cr", "Cr"),
                    ("BUN", "BUN"),
                    ("FBS", "FBS"),
                    ("Uric_Acid", "Uric_Acid"),
                    ("Na", "Na"),
                    ("K", "K"),
                    ("Ca", "Ca"),
                    ("P", "P"),
                    ("ALT", "ALT"),
                    ("AST", "AST"),
                    ("AlkPh", "AlkPh"),
                    ("Tg", "Tg"),
                    ("Chol", "Chol"),
                    ("LDL", "LDL"),
                    ("HDL", "HDL"),
                    ("HbA1c", "HbA1c"),
                    ("Fe", "Fe"),
                    ("Ferritin", "Ferritin"),
                    ("TIBC", "TIBC"),
                    ("CPK_total", "CPK_total"),
                    ("Vit_D3", "Vit_D3"),
                    ("PTH", "PTH"),
                    ("T3", "T3"),
                    ("T4", "T4"),
                    ("TSH", "TSH"),
                    ("Free_Beta_HCG", "Free_Beta_HCG"),
                    ("urine24_result", "urine24_result"),
                    ("urine24_volume", "urine24_volume"),
                    ("urine24_cr", "urine24_cr"),
                    ("urine24_protein", "urine24_protein"),
                    ("urine_blood", "urine_blood"),
                    ("urine_protein", "urine_protein"),
                    ("urine_hemoglobin", "urine_hemoglobin"),
                    ("urine_glucose", "urine_glucose"),
                    ("wbc_range", "wbc_range"),
                    ("rbc_range", "rbc_range"),
                    ("Urine Culture", "Urine Culture"),
                    ("urine_culture_count", "urine_culture_count"),
                    ("HBs Ag", "HBs Ag"),
                    ("IGRA", "IGRA"),
                    ("Widal Test", "Widal Test"),
                    ("VDRL", "VDRL"),
                    ("Wright Test", "Wright Test"),
                    ("RF [Qual]", "RF [Qual]"),
                    ("PT & INR", "PT & INR"),
                    ("CMV IgM", "CMV IgM"),
                    ("Toxoplasma gondii IgG", "Toxoplasma gondii IgG"),
                    ("Toxoplasma gondii IgM", "Toxoplasma gondii IgM"),
                    ("PTT", "PTT"),
                    ("HSV 1&2 IgM", "HSV 1&2 IgM"),
                    ("Coombs Wright", "Coombs Wright"),
                    ("HSV 2 IgG", "HSV 2 IgG"),
                    ("EBV Capsid IgM", "EBV Capsid IgM"),
                    ("VZV IgG", "VZV IgG"),
                    ("VZV IgM", "VZV IgM"),
                    ("Anti HBs", "Anti HBs"),
                    ("Anti HCV", "Anti HCV"),
                    ("CMV IgG", "CMV IgG"),
                    ("UA", "UA"),
                    ("HTLV I+II", "HTLV I+II"),
                    ("HTLV I Ab", "HTLV I Ab"),
                    ("HIV Ab & P24 Ag", "HIV Ab & P24 Ag"),
                ],
                max_length=160,
            ),
        ),
        migrations.AlterField(
            model_name="person",
            name="identifier",
            field=models.CharField(
                max_length=40, unique=True, verbose_name="کد ملی یا شماره گذرنامه"
            ),
        ),
        migrations.AddField(
            model_name="antihlatest",
            name="created_by",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="registered_anti_hla_tests",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="antihlatest",
            name="person",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="anti_hla_tests",
                to="registry.person",
            ),
        ),
        migrations.AddField(
            model_name="antihlaselection",
            name="test",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="selections",
                to="registry.antihlatest",
            ),
        ),
        migrations.AddField(
            model_name="cdcpratest",
            name="created_by",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="registered_cdc_pra_tests",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="cdcpratest",
            name="person",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="cdc_pra_tests",
                to="registry.person",
            ),
        ),
        migrations.AddField(
            model_name="hlaselection",
            name="typing",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="selections",
                to="registry.hlatyping",
            ),
        ),
        migrations.RunPython(
            migrate_existing_immunology_data,
            reverse_code=migrations.RunPython.noop,
        ),
        migrations.RemoveField(
            model_name="hlatyping",
            name="hla_a",
        ),
        migrations.RemoveField(
            model_name="hlatyping",
            name="hla_b",
        ),
        migrations.RemoveField(
            model_name="hlatyping",
            name="hla_c",
        ),
        migrations.RemoveField(
            model_name="hlatyping",
            name="hla_dqb1",
        ),
        migrations.RemoveField(
            model_name="hlatyping",
            name="hla_drb",
        ),
        migrations.RemoveField(
            model_name="hlatyping",
            name="hla_drb1",
        ),
        migrations.AddConstraint(
            model_name="antihlatest",
            constraint=models.UniqueConstraint(
                fields=("person", "performed_at"),
                name="registry_anti_hla_person_date_unique",
            ),
        ),
        migrations.AddConstraint(
            model_name="antihlatest",
            constraint=models.CheckConstraint(
                condition=models.Q(("expires_at__gte", models.F("performed_at"))),
                name="registry_anti_hla_expiry_after_performed",
            ),
        ),
        migrations.AddConstraint(
            model_name="antihlaselection",
            constraint=models.UniqueConstraint(
                fields=("test", "locus", "antigen"),
                name="registry_anti_hla_selection_unique",
            ),
        ),
        migrations.AddConstraint(
            model_name="cdcpratest",
            constraint=models.UniqueConstraint(
                fields=("person", "performed_at"),
                name="registry_cdc_person_date_unique",
            ),
        ),
        migrations.AddConstraint(
            model_name="cdcpratest",
            constraint=models.CheckConstraint(
                condition=models.Q(("expires_at__gte", models.F("performed_at"))),
                name="registry_cdc_expiry_after_performed",
            ),
        ),
        migrations.AddConstraint(
            model_name="hlaselection",
            constraint=models.UniqueConstraint(
                fields=("typing", "locus", "allele"),
                name="registry_hla_selection_unique",
            ),
        ),
    ]
