# Generated by Django 5.1.1 on 2026-08-06 12:54

import django.core.validators
import django.db.models.deletion
import registry.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "registry",
            "0002_antihlaselection_antihlatest_cdcpratest_hlaselection_and_more",
        ),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AllocationPolicy",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=120)),
                ("version", models.PositiveIntegerField(default=1)),
                ("is_active", models.BooleanField(default=False)),
                (
                    "hla_weight",
                    models.DecimalField(decimal_places=4, default=0.35, max_digits=5),
                ),
                (
                    "waiting_time_weight",
                    models.DecimalField(decimal_places=4, default=0.2, max_digits=5),
                ),
                (
                    "urgency_weight",
                    models.DecimalField(decimal_places=4, default=0.2, max_digits=5),
                ),
                (
                    "cpra_weight",
                    models.DecimalField(decimal_places=4, default=0.15, max_digits=5),
                ),
                (
                    "age_weight",
                    models.DecimalField(decimal_places=4, default=0.05, max_digits=5),
                ),
                (
                    "regional_weight",
                    models.DecimalField(decimal_places=4, default=0.05, max_digits=5),
                ),
                (
                    "locus_weights",
                    models.JSONField(default=registry.models.default_locus_weights),
                ),
                ("high_cpra_threshold", models.PositiveSmallIntegerField(default=80)),
                (
                    "high_cpra_hla_discount",
                    models.DecimalField(decimal_places=4, default=0.6, max_digits=5),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "سیاست تخصیص",
                "verbose_name_plural": "سیاست\u200cهای تخصیص",
                "ordering": ("-version",),
            },
        ),
        migrations.CreateModel(
            name="ClinicalStateEvent",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "entity_type",
                    models.CharField(
                        choices=[("recipient", "گیرنده"), ("donor", "اهداکننده")],
                        max_length=12,
                    ),
                ),
                ("previous_status", models.CharField(blank=True, max_length=32)),
                ("new_status", models.CharField(max_length=32)),
                ("reason", models.TextField()),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "رویداد تغییر وضعیت",
                "verbose_name_plural": "رویدادهای تغییر وضعیت",
                "ordering": ("-created_at",),
            },
        ),
        migrations.CreateModel(
            name="CrossMatchRequest",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("consultation_requested", "درخواست مشاوره"),
                            ("center_review", "در بررسی مرکز"),
                            ("scheduled", "برنامه\u200cریزی شده"),
                            ("negative", "منفی"),
                            ("positive", "مثبت"),
                            ("cancelled", "لغو شده"),
                        ],
                        default="consultation_requested",
                        max_length=24,
                    ),
                ),
                ("patient_note", models.TextField(blank=True)),
                ("physician_note", models.TextField(blank=True)),
                ("scheduled_at", models.DateTimeField(blank=True, null=True)),
                ("result_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ("-created_at",),
            },
        ),
        migrations.CreateModel(
            name="InAppNotification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("new_match", "تطبیق جدید"),
                            ("state_changed", "تغییر وضعیت"),
                            ("test_expiry", "انقضای آزمایش"),
                            ("crossmatch", "Cross-Match"),
                        ],
                        max_length=20,
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("body", models.TextField()),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("dedupe_key", models.CharField(blank=True, max_length=200)),
                ("read_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ("-created_at",),
            },
        ),
        migrations.CreateModel(
            name="MatchingRun",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "trigger",
                    models.CharField(
                        choices=[
                            ("nightly", "شبانه"),
                            ("donor_created", "ثبت اهداکننده"),
                            ("anti_hla_updated", "تغییر Anti-HLA"),
                            ("manual", "دستی"),
                        ],
                        max_length=24,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("running", "در حال اجرا"),
                            ("completed", "تکمیل شده"),
                            ("failed", "ناموفق"),
                        ],
                        default="running",
                        max_length=12,
                    ),
                ),
                ("statistics", models.JSONField(blank=True, default=dict)),
                ("error", models.TextField(blank=True)),
                ("started_at", models.DateTimeField(auto_now_add=True)),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "ordering": ("-started_at",),
            },
        ),
        migrations.CreateModel(
            name="MatchProposal",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "compatibility",
                    models.CharField(
                        choices=[
                            ("compatible", "سازگار"),
                            ("conditional", "سازگار مشروط"),
                            ("incompatible", "ناسازگار"),
                        ],
                        max_length=16,
                    ),
                ),
                (
                    "decision",
                    models.CharField(
                        choices=[
                            ("proposed", "پیشنهاد شده"),
                            ("approved", "تأیید مرکز"),
                            ("rejected", "رد مرکز"),
                            ("crossmatch_negative", "Cross-Match منفی"),
                            ("crossmatch_positive", "Cross-Match مثبت"),
                            ("closed", "بسته شده"),
                        ],
                        default="proposed",
                        max_length=24,
                    ),
                ),
                ("rank", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "final_score",
                    models.DecimalField(decimal_places=4, default=0, max_digits=8),
                ),
                ("abo_compatible", models.BooleanField(default=False)),
                ("anti_hla_status", models.CharField(max_length=16)),
                ("hla_summary", models.JSONField(default=dict)),
                ("score_breakdown", models.JSONField(default=dict)),
                ("rejection_reasons", models.JSONField(blank=True, default=list)),
                ("warnings", models.JSONField(blank=True, default=list)),
                ("center_note", models.TextField(blank=True)),
                ("decided_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "پیشنهاد تطبیق",
                "verbose_name_plural": "پیشنهادهای تطبیق",
                "ordering": ("recipient_id", "rank", "-final_score"),
            },
        ),
        migrations.CreateModel(
            name="SensitiveDataAccessLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("data_type", models.CharField(default="HLA", max_length=32)),
                ("purpose", models.CharField(max_length=120)),
                ("source_ip", models.GenericIPAddressField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ("-created_at",),
            },
        ),
        migrations.AddField(
            model_name="donorprofile",
            name="status",
            field=models.CharField(
                choices=[
                    ("registered", "ثبت\u200cنام اولیه"),
                    ("medical_screening", "در غربالگری پزشکی"),
                    ("available", "در دسترس برای Matching"),
                    ("match_candidate", "کاندیدای اهدا"),
                    ("awaiting_crossmatch", "در انتظار Cross-Match"),
                    ("ready", "آماده عمل"),
                    ("donated", "اهدا انجام شد"),
                    ("follow_up", "پیگیری پس از اهدا"),
                    ("reserved", "رزرو شده برای گیرنده خاص"),
                    ("suspended", "معلق"),
                    ("permanent_deferral", "منع دائم پزشکی"),
                ],
                default="medical_screening",
                max_length=32,
            ),
        ),
        migrations.AddField(
            model_name="hlaselection",
            name="copy_number",
            field=models.PositiveSmallIntegerField(
                default=1,
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(2),
                ],
            ),
        ),
        migrations.AddField(
            model_name="recipientprofile",
            name="medical_urgency",
            field=models.PositiveSmallIntegerField(
                default=0,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(100),
                ],
            ),
        ),
        migrations.AddField(
            model_name="recipientprofile",
            name="regional_disadvantage",
            field=models.PositiveSmallIntegerField(
                default=0,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(100),
                ],
            ),
        ),
        migrations.AddField(
            model_name="recipientprofile",
            name="status",
            field=models.CharField(
                choices=[
                    ("registered", "ثبت\u200cنام اولیه"),
                    ("pending_documents", "در انتظار تأیید مدارک"),
                    ("rejected", "رد شده"),
                    ("active", "فعال در لیست انتظار"),
                    ("match_candidate", "کاندیدای تطبیق"),
                    ("awaiting_crossmatch", "در انتظار Cross-Match"),
                    ("awaiting_high_resolution", "در انتظار High-Resolution"),
                    ("ready", "آماده پیوند"),
                    ("transplanted", "پیوند انجام شد"),
                    ("follow_up", "پیگیری پس از پیوند"),
                    ("temporarily_inactive", "غیرفعال موقت"),
                    ("removed", "حذف از لیست انتظار"),
                ],
                default="pending_documents",
                max_length=32,
            ),
        ),
        migrations.AddField(
            model_name="recipientprofile",
            name="waiting_since",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name="antihlaselection",
            index=models.Index(
                fields=["locus", "antigen", "test"], name="registry_antihla_inv_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="donorprofile",
            index=models.Index(
                fields=["status", "updated_at"], name="registry_donor_status_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="hlaselection",
            index=models.Index(
                fields=["locus", "allele", "typing"], name="registry_hla_inverted_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="recipientprofile",
            index=models.Index(
                fields=["status", "waiting_since"], name="registry_rec_wait_idx"
            ),
        ),
        migrations.AddField(
            model_name="allocationpolicy",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="allocation_policies",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="clinicalstateevent",
            name="actor",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="clinical_state_events",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="clinicalstateevent",
            name="donor",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="state_events",
                to="registry.donorprofile",
            ),
        ),
        migrations.AddField(
            model_name="clinicalstateevent",
            name="recipient",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="state_events",
                to="registry.recipientprofile",
            ),
        ),
        migrations.AddField(
            model_name="crossmatchrequest",
            name="donor",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="crossmatch_requests",
                to="registry.donorprofile",
            ),
        ),
        migrations.AddField(
            model_name="crossmatchrequest",
            name="recipient",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="crossmatch_requests",
                to="registry.recipientprofile",
            ),
        ),
        migrations.AddField(
            model_name="crossmatchrequest",
            name="requested_by",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="requested_crossmatches",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="crossmatchrequest",
            name="reviewed_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="reviewed_crossmatches",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="inappnotification",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="registry_notifications",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="matchingrun",
            name="initiated_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="matching_runs",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="matchingrun",
            name="policy",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="matching_runs",
                to="registry.allocationpolicy",
            ),
        ),
        migrations.AddField(
            model_name="matchproposal",
            name="decided_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="decided_match_proposals",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="matchproposal",
            name="donor",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="match_proposals",
                to="registry.donorprofile",
            ),
        ),
        migrations.AddField(
            model_name="matchproposal",
            name="recipient",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="match_proposals",
                to="registry.recipientprofile",
            ),
        ),
        migrations.AddField(
            model_name="matchproposal",
            name="run",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="proposals",
                to="registry.matchingrun",
            ),
        ),
        migrations.AddField(
            model_name="crossmatchrequest",
            name="proposal",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="crossmatch_requests",
                to="registry.matchproposal",
            ),
        ),
        migrations.AddField(
            model_name="sensitivedataaccesslog",
            name="person",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="sensitive_data_accesses",
                to="registry.person",
            ),
        ),
        migrations.AddField(
            model_name="sensitivedataaccesslog",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="sensitive_data_accesses",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddConstraint(
            model_name="allocationpolicy",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_active", True)),
                fields=("is_active",),
                name="registry_one_active_policy",
            ),
        ),
        migrations.AddIndex(
            model_name="clinicalstateevent",
            index=models.Index(
                fields=["entity_type", "created_at"], name="registry_state_event_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="clinicalstateevent",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("donor__isnull", True),
                        ("entity_type", "recipient"),
                        ("recipient__isnull", False),
                    ),
                    models.Q(
                        ("donor__isnull", False),
                        ("entity_type", "donor"),
                        ("recipient__isnull", True),
                    ),
                    _connector="OR",
                ),
                name="registry_state_event_one_entity",
            ),
        ),
        migrations.AddConstraint(
            model_name="inappnotification",
            constraint=models.UniqueConstraint(
                condition=models.Q(("dedupe_key", ""), _negated=True),
                fields=("user", "dedupe_key"),
                name="registry_notification_dedupe",
            ),
        ),
        migrations.AddIndex(
            model_name="matchproposal",
            index=models.Index(
                fields=["recipient", "compatibility", "decision", "rank"],
                name="registry_match_rec_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="matchproposal",
            index=models.Index(
                fields=["donor", "compatibility", "decision"],
                name="registry_match_donor_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="matchproposal",
            constraint=models.UniqueConstraint(
                fields=("run", "recipient", "donor"), name="registry_run_pair_unique"
            ),
        ),
        migrations.AddConstraint(
            model_name="crossmatchrequest",
            constraint=models.UniqueConstraint(
                condition=models.Q(
                    (
                        "status__in",
                        ("consultation_requested", "center_review", "scheduled"),
                    )
                ),
                fields=("proposal",),
                name="registry_one_open_crossmatch",
            ),
        ),
        migrations.AddIndex(
            model_name="sensitivedataaccesslog",
            index=models.Index(
                fields=["person", "data_type", "created_at"],
                name="registry_sensitive_log_idx",
            ),
        ),
    ]
