# Generated by Django 5.1.1 on 2026-08-06 13:02

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("registry", "0003_allocationpolicy_clinicalstateevent_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="allocationpolicy",
            name="age_weight",
            field=models.DecimalField(
                decimal_places=4, default=Decimal("0.05"), max_digits=5
            ),
        ),
        migrations.AlterField(
            model_name="allocationpolicy",
            name="cpra_weight",
            field=models.DecimalField(
                decimal_places=4, default=Decimal("0.15"), max_digits=5
            ),
        ),
        migrations.AlterField(
            model_name="allocationpolicy",
            name="high_cpra_hla_discount",
            field=models.DecimalField(
                decimal_places=4, default=Decimal("0.60"), max_digits=5
            ),
        ),
        migrations.AlterField(
            model_name="allocationpolicy",
            name="hla_weight",
            field=models.DecimalField(
                decimal_places=4, default=Decimal("0.35"), max_digits=5
            ),
        ),
        migrations.AlterField(
            model_name="allocationpolicy",
            name="regional_weight",
            field=models.DecimalField(
                decimal_places=4, default=Decimal("0.05"), max_digits=5
            ),
        ),
        migrations.AlterField(
            model_name="allocationpolicy",
            name="urgency_weight",
            field=models.DecimalField(
                decimal_places=4, default=Decimal("0.20"), max_digits=5
            ),
        ),
        migrations.AlterField(
            model_name="allocationpolicy",
            name="waiting_time_weight",
            field=models.DecimalField(
                decimal_places=4, default=Decimal("0.20"), max_digits=5
            ),
        ),
    ]
