# Generated by Django 5.1.1 on 2026-08-06 13:09

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("registry", "0006_alter_hlaselection_allele_alter_hlaselection_locus"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="crossmatchrequest",
            name="registry_one_open_crossmatch",
        ),
        migrations.AlterField(
            model_name="crossmatchrequest",
            name="status",
            field=models.CharField(
                choices=[
                    ("consultation_requested", "درخواست مشاوره"),
                    ("center_review", "در بررسی مرکز"),
                    ("scheduled", "برنامه\u200cریزی شده"),
                    ("awaiting_high_resolution", "در انتظار High-Resolution"),
                    ("negative", "منفی"),
                    ("positive", "مثبت"),
                    ("cancelled", "لغو شده"),
                ],
                default="consultation_requested",
                max_length=24,
            ),
        ),
        migrations.AddConstraint(
            model_name="crossmatchrequest",
            constraint=models.UniqueConstraint(
                condition=models.Q(
                    (
                        "status__in",
                        (
                            "consultation_requested",
                            "center_review",
                            "scheduled",
                            "awaiting_high_resolution",
                        ),
                    )
                ),
                fields=("proposal",),
                name="registry_one_open_crossmatch",
            ),
        ),
    ]
