# Generated by Django 5.2.6 on 2026-08-06 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "registry",
            "0007_remove_crossmatchrequest_registry_one_open_crossmatch_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="recipientprofile",
            name="emergency_reason",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="recipientprofile",
            name="is_emergency",
            field=models.BooleanField(default=False),
        ),
    ]
