# Generated by Django 5.2.6 on 2026-08-06 18:55

from django.db import migrations, models


LOW_RESOLUTION_VALUES = {
    "A": set("A*01 A*02 A*03 A*11 A*23 A*24 A*25 A*26 A*29 A*30 A*31 A*32 A*33 A*34 A*36 A*43 A*66 A*68 A*69 A*74 A*80".split()),
    "B": set("B*07 B*08 B*13 B*14 B*15 B*18 B*27 B*35 B*37 B*38 B*39 B*40 B*41 B*42 B*44 B*45 B*46 B*47 B*48 B*49 B*50 B*51 B*52 B*53 B*54 B*55 B*56 B*57 B*58 B*59 B*67 B*73 B*78 B*81 B*82 B*83".split()),
    "C": set("C*01 C*02 C*03 C*04 C*05 C*06 C*07 C*08 C*12 C*14 C*15 C*16 C*17 C*18".split()),
    "DRB1": set("DRB1*01 DRB1*03 DRB1*04 DRB1*07 DRB1*08 DRB1*09 DRB1*10 DRB1*11 DRB1*12 DRB1*13 DRB1*14 DRB1*15 DRB1*16".split()),
    "DQB1": set("DQB1*02 DQB1*03 DQB1*04 DQB1*05 DQB1*06".split()),
    "DRB": {"DRB3", "DRB4", "DRB5", "سایر"},
}


def normalize_existing_hla(apps, schema_editor):
    HLASelection = apps.get_model("registry", "HLASelection")
    for selection in HLASelection.objects.order_by("typing_id", "locus", "id").iterator():
        allowed = LOW_RESOLUTION_VALUES.get(selection.locus)
        if allowed is None:
            selection.delete()
            continue
        normalized = selection.allele
        if normalized not in allowed:
            normalized = (
                normalized.split("*", 1)[0]
                if selection.locus == "DRB"
                else normalized.split(":", 1)[0]
            )
        if normalized not in allowed:
            selection.delete()
            continue
        duplicate = HLASelection.objects.filter(
            typing_id=selection.typing_id,
            locus=selection.locus,
            allele=normalized,
        ).exclude(pk=selection.pk).first()
        if duplicate:
            duplicate.copy_number = min(2, duplicate.copy_number + selection.copy_number)
            duplicate.save(update_fields=("copy_number",))
            selection.delete()
        elif selection.allele != normalized:
            selection.allele = normalized
            selection.save(update_fields=("allele",))


class Migration(migrations.Migration):

    dependencies = [
        ("registry", "0009_preserve_sensitive_log_identity"),
    ]

    operations = [
        migrations.RunPython(normalize_existing_hla, migrations.RunPython.noop),
        migrations.AlterField(
            model_name="hlaselection",
            name="allele",
            field=models.CharField(
                choices=[
                    ("A*01", "A*01"),
                    ("A*02", "A*02"),
                    ("A*03", "A*03"),
                    ("A*11", "A*11"),
                    ("A*23", "A*23"),
                    ("A*24", "A*24"),
                    ("A*25", "A*25"),
                    ("A*26", "A*26"),
                    ("A*29", "A*29"),
                    ("A*30", "A*30"),
                    ("A*31", "A*31"),
                    ("A*32", "A*32"),
                    ("A*33", "A*33"),
                    ("A*34", "A*34"),
                    ("A*36", "A*36"),
                    ("A*43", "A*43"),
                    ("A*66", "A*66"),
                    ("A*68", "A*68"),
                    ("A*69", "A*69"),
                    ("A*74", "A*74"),
                    ("A*80", "A*80"),
                    ("B*07", "B*07"),
                    ("B*08", "B*08"),
                    ("B*13", "B*13"),
                    ("B*14", "B*14"),
                    ("B*15", "B*15"),
                    ("B*18", "B*18"),
                    ("B*27", "B*27"),
                    ("B*35", "B*35"),
                    ("B*37", "B*37"),
                    ("B*38", "B*38"),
                    ("B*39", "B*39"),
                    ("B*40", "B*40"),
                    ("B*41", "B*41"),
                    ("B*42", "B*42"),
                    ("B*44", "B*44"),
                    ("B*45", "B*45"),
                    ("B*46", "B*46"),
                    ("B*47", "B*47"),
                    ("B*48", "B*48"),
                    ("B*49", "B*49"),
                    ("B*50", "B*50"),
                    ("B*51", "B*51"),
                    ("B*52", "B*52"),
                    ("B*53", "B*53"),
                    ("B*54", "B*54"),
                    ("B*55", "B*55"),
                    ("B*56", "B*56"),
                    ("B*57", "B*57"),
                    ("B*58", "B*58"),
                    ("B*59", "B*59"),
                    ("B*67", "B*67"),
                    ("B*73", "B*73"),
                    ("B*78", "B*78"),
                    ("B*81", "B*81"),
                    ("B*82", "B*82"),
                    ("B*83", "B*83"),
                    ("C*01", "C*01"),
                    ("C*02", "C*02"),
                    ("C*03", "C*03"),
                    ("C*04", "C*04"),
                    ("C*05", "C*05"),
                    ("C*06", "C*06"),
                    ("C*07", "C*07"),
                    ("C*08", "C*08"),
                    ("C*12", "C*12"),
                    ("C*14", "C*14"),
                    ("C*15", "C*15"),
                    ("C*16", "C*16"),
                    ("C*17", "C*17"),
                    ("C*18", "C*18"),
                    ("DRB1*01", "DRB1*01"),
                    ("DRB1*03", "DRB1*03"),
                    ("DRB1*04", "DRB1*04"),
                    ("DRB1*07", "DRB1*07"),
                    ("DRB1*08", "DRB1*08"),
                    ("DRB1*09", "DRB1*09"),
                    ("DRB1*10", "DRB1*10"),
                    ("DRB1*11", "DRB1*11"),
                    ("DRB1*12", "DRB1*12"),
                    ("DRB1*13", "DRB1*13"),
                    ("DRB1*14", "DRB1*14"),
                    ("DRB1*15", "DRB1*15"),
                    ("DRB1*16", "DRB1*16"),
                    ("DQB1*02", "DQB1*02"),
                    ("DQB1*03", "DQB1*03"),
                    ("DQB1*04", "DQB1*04"),
                    ("DQB1*05", "DQB1*05"),
                    ("DQB1*06", "DQB1*06"),
                    ("DRB3", "DRB3"),
                    ("DRB4", "DRB4"),
                    ("DRB5", "DRB5"),
                    ("سایر", "سایر"),
                ],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="hlaselection",
            name="locus",
            field=models.CharField(
                choices=[
                    ("A", "HLA-A"),
                    ("B", "HLA-B"),
                    ("C", "HLA-C"),
                    ("DRB1", "HLA-DRB1"),
                    ("DQB1", "HLA-DQB1"),
                    ("DRB", "HLA-DRB"),
                ],
                max_length=4,
            ),
        ),
    ]
