# Generated by Django 5.2.6 on 2026-08-07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("registry", "0010_alter_hlaselection_allele_alter_hlaselection_locus"),
    ]

    operations = [
        migrations.AlterField(
            model_name="matchproposal",
            name="compatibility",
            field=models.CharField(
                choices=[
                    ("compatible", "سازگار"),
                    ("conditional", "سازگار مشروط"),
                    ("incompatible", "ناسازگار"),
                    ("insufficient-data", "اطلاعات ناکافی"),
                ],
                max_length=24,
            ),
        ),
    ]
