# Generated by Django 5.2.6 on 2026-08-04 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="notify_email_approvals",
            field=models.BooleanField(
                default=True, verbose_name="ایمیل یادآوری تأییدیه\u200cها"
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="notify_email_new_match",
            field=models.BooleanField(default=True, verbose_name="ایمیل تطابق جدید"),
        ),
        migrations.AddField(
            model_name="user",
            name="notify_in_app_match",
            field=models.BooleanField(
                default=True, verbose_name="اعلان درون\u200cبرنامه\u200cای تطابق"
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="notify_in_app_messages",
            field=models.BooleanField(
                default=True, verbose_name="اعلان درون\u200cبرنامه\u200cای پیام\u200cها"
            ),
        ),
    ]
