# Generated by Django 5.2.6 on 2026-08-06 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_user_notify_email_approvals_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="coordinator_level",
            field=models.CharField(
                choices=[
                    ("level_one", "هماهنگ\u200cکننده پیوند سطح یک"),
                    ("level_two", "هماهنگ\u200cکننده پیوند سطح دو"),
                ],
                default="level_two",
                max_length=16,
                verbose_name="سطح هماهنگ\u200cکننده",
            ),
        ),
    ]
